export default Object.freeze({
    WELCOME: "WelcomeScreen",
    AUTHENTICATION: "AuthenticationScreen",
    VERIFYOTP: "VerifyOTPScreen",
    HOMEAPPSCREEN: "HomeAppScreen",
    SERVICESROUTE: "ServicesRoute",
    ACTIVITYAPPSCREEN: "ActivityAppScreen",
    SERVICESAPPSCREEN: "ServicesAppScreen",
    PROFILEROUTE: "ProfileRoute",
    PROFILEAPPSCREEN: "ProfileAppScreen",
    AMBULANCETYPEINFO: "AmbulanceTypeInfoScreen",
    HELPSCREEN: "HelpScreen",
    WALLETSCREEN: "WalletScreen",
    RIDESCREEN: "RideScreen",
    MESSAGESCREEN: "MessageScreen",
    COUPONSCREEN: "CouponsScreen",
    REFERSCREEN: "ReferScreen",
    SETTINGSCREEN: "SettingsScreen",
    LEGALSCREEN: "LegalScreen",
})